FROM gradle:7.6.0-jdk17 as builder
COPY ./ ./
RUN gradle clean bootJar

FROM eclipse-temurin:17

WORKDIR /usr/src/app

COPY --from=builder /home/gradle/build/libs/*.jar application.jar

EXPOSE 8181
EXPOSE 8010

ENTRYPOINT java -jar "application.jar" \
            -Dspring.profiles.active=$SPRING_PROFILES_ACTIVE \
            -DSPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL \
            -DSPRING_DATASOURCE_USERNAME=$SPRING_DATASOURCE_USERNAME \
            -DSPRING_DATASOURCE_PASSWORD=$SPRING_DATASOURCE_PASSWORD \
            -DHIKARI_MIN_IDLE=$HIKARI_MIN_IDLE \
            -DHIKARI_MAX_POOL_SIZE=$HIKARI_MAX_POOL_SIZE \
            -DHIKARI_CONNECTION_TIMEOUT=$HIKARI_CONNECTION_TIMEOUT \
            -OTEL_EXPORTER_ENDPOINT=$OTEL_EXPORTER_ENDPOINT