### Create a new customer
POST localhost:9999/customer
Content-type: application/json

{
  "name": "Andre Lucas AI",
  "email": "andrelucastic@gmail.com"
}

###
@customerId = 37746893-c181-4ebc-ac9f-3f8988542d30

### Create a new toilet
POST localhost:8181/toilet
Content-type: application/json

{
    "description": "Toilet 1",
    "latitude": 9.4323,
    "longitude": -19.333,
    "customerId": "{{customerId}}"
}

###
@toiletId = c9c87ce4-9c5d-44d4-9abb-19a6a3d1c6f8

### Add a new  item
POST localhost:9999/toilet/{{toiletId}}/item
Content-type: application/json

{
    "description": "Item35"
}