### Create a new customer
POST localhost/customer
Content-type: application/json

{
  "name": "Andre Lucas Ingress",
  "email": "andrelucastic@gmail.com"
}

###
@customerId = bae0fdce-1868-4cec-94a7-7ec83f86c1c3

### Create a new toilet
POST localhost/toilet
Content-type: application/json

{
    "description": "Toilet Ingress 5",
    "latitude": 9.4323,
    "longitude": -19.333,
    "customerId": "{{customerId}}"
}

###
@toiletId = 94ff253e-65a8-40cb-9c55-260faa1a6b45

### Add a new  item
POST localhost:8181/toilet/{{toiletId}}/item
Content-type: application/json

{
    "description": "Item35"
}