spring:
  application:
    name: toilet-near-me
  datasource:
    url: jdbc:postgresql://localhost:5432/toilet
    username: toilet
    password: toilet
  jpa:
    show-sql: true
    open-in-view: false

otel:
  exporter:
    endpoint: http://otel-collector:4317

server:
  port: 8181
org:
  jobrunr:
    background-job-server:
      enabled: true
    dashboard:
      enabled: false
