spring:
  application:
    name: toilet-near-me
  datasource:
    url: jdbc:postgresql://localhost:5432/toilet
    username: toilet
    password: toilet
  jpa:
    show-sql: false
    open-in-view: false


otel:
  exporter:
      endpoint: http://localhost:4317

server:
  port: 8181
org:
  jobrunr:
    background-job-server:
      enabled: true
    dashboard:
      enabled: true
      port: 8010
