apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: toilet-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: toilet
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 40