apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kong-metrics
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: kong
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
