apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: toilet-rate-limit
config:
  second: 10
  limit_by: header
  policy: local
  header_name: X-Credential-Identifier
plugin: rate-limiting