apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: toilet
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
      repoURL: https://github.com/andrelucasti/toilet-near-me-java.git
      targetRevision: HEAD
      path: infraascode/k8s
  destination:
      server: https://kubernetes.default.svc
      namespace: toilet-near-me
  syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace