name: API Contract Tests
on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: OpenAPI document validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate OpenAPI document - Spectral
        uses: stoplightio/spectral-action@latest
        with:
         file_glob: '*.oas.{json,yml,yaml}'
         spectral_ruleset: 'openapi.spectral.yaml'
