name: toilet-ci

on:
  push:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup DB
        run: docker run -d --name postgresql.toilet-near-me -e POSTGRES_PASSWORD=toilet -e POSTGRES_USER=toilet -e POSTGRES_DB=toilet -p 5432:5432 postgres:latest

      - name: Set up gradle
        uses: gradle/gradle-build-action@v3.5.0

      - name: Test with Gradle
        run: ./gradlew clean test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up gradle
        uses: gradle/gradle-build-action@v3.5.0

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name : Build Docker image
        run: docker build -t andrelucastic/toilet-near-me-java:1.2.0 .

      - name: Push Docker image
        run: docker push andrelucastic/toilet-near-me-java:1.2.0

